package com.hoatv.exam.integrity.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * Embedded question within an ExamDraft, carrying both the parsed content
 * AND the integrity/confidence metadata needed for the teacher review UI.
 *
 * This is the PRE-PUBLICATION form of a question.
 * After teacher approval it is converted to a plain {@link Question}.
 */
public class DraftQuestion {

    /** UUID generated at parse time. Becomes Question.id on publish. */
    private String id;

    /** 1-based display order as detected by the parser. Teacher can reorder. */
    private int questionNumber;

    /**
     * Normalized question text (Unicode math symbols applied, LaTeX stripped).
     * Teacher can edit this field during review.
     */
    private String content;

    /**
     * Raw text extracted from the PDF before normalization.
     * Shown in the review UI alongside content so teacher can spot OCR errors.
     * Read-only; never sent back to the client after review.
     */
    private String rawText;

    private Question.QuestionType type;

    private double points;

    /** MCQ options as parsed. Teacher can edit/add/remove options. */
    private List<String> options = new ArrayList<>();

    /**
     * Correct answer as detected by the parser (MCQ) or left blank (essay).
     * Teacher must fill this in for essay questions before approving.
     */
    private String correctAnswer;

    /**
     * Essay rubric. Null on initial parse; teacher fills this in during review
     * for ESSAY_SHORT and ESSAY_LONG questions before approving.
     */
    private Rubric rubric;

    /** True when the parser detected the question text was cut by a page break. */
    private boolean truncated;

    // ── Integrity metadata (read-only, set by ingestion service) ────────────

    /**
     * Mean OCR confidence for this question's text block (0.0–1.0).
     * null for text-based PDF pages.
     * Review UI shows a warning badge when value < 0.75.
     */
    private Double ocrConfidence;

    /**
     * Parser structural confidence (0.0–1.0).
     * Reflects how certain the parser was about:
     * - question boundary detection
     * - point value extraction
     * - question type classification
     * Review UI shows a warning badge when value < 0.80.
     */
    private double parserConfidence;

    /** PDF page number (1-based) where this question was found. */
    private Integer pageNumber;

    /**
     * Bounding box on the scanned page. Used by the review UI to render
     * an "image crop" preview of the original scan alongside the parsed text.
     * null for text-based PDFs.
     */
    private BoundingBox boundingBox;

    /**
     * Per-question warnings generated by the parser.
     * Examples:
     *   - "Point value not found; defaulted to 0.5"
     *   - "MCQ option D missing"
     *   - "Question text appears truncated at page break"
     *   - "Low OCR confidence (0.61) — verify content manually"
     */
    private List<String> parserWarnings = new ArrayList<>();

    // ── Review state (set by teacher during review) ──────────────────────────

    private ReviewStatus reviewStatus;

    /**
     * Teacher's note attached during review.
     * E.g. "Corrected OCR error: 'S' was read as '5'"
     */
    private String teacherNotes;

    public enum ReviewStatus {
        /** Not yet looked at by teacher. */
        PENDING,
        /** Teacher confirmed the parsed content is correct. */
        APPROVED,
        /** Teacher edited the content and confirmed the correction. */
        CORRECTED,
        /** Teacher flagged this question for exclusion (e.g. scan too damaged). */
        EXCLUDED
    }

    /**
     * Pixel bounding box of the question block in the source scanned image.
     */
    public static class BoundingBox {
        private int pageNumber;
        private float x1, y1, x2, y2;

        public int getPageNumber() { return pageNumber; }
        public void setPageNumber(int pageNumber) { this.pageNumber = pageNumber; }

        public float getX1() { return x1; }
        public void setX1(float x1) { this.x1 = x1; }

        public float getY1() { return y1; }
        public void setY1(float y1) { this.y1 = y1; }

        public float getX2() { return x2; }
        public void setX2(float x2) { this.x2 = x2; }

        public float getY2() { return y2; }
        public void setY2(float y2) { this.y2 = y2; }
    }

    // ----- Getters & Setters -----

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public int getQuestionNumber() { return questionNumber; }
    public void setQuestionNumber(int questionNumber) { this.questionNumber = questionNumber; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public String getRawText() { return rawText; }
    public void setRawText(String rawText) { this.rawText = rawText; }

    public Question.QuestionType getType() { return type; }
    public void setType(Question.QuestionType type) { this.type = type; }

    public double getPoints() { return points; }
    public void setPoints(double points) { this.points = points; }

    public List<String> getOptions() { return options; }
    public void setOptions(List<String> options) { this.options = options; }

    public String getCorrectAnswer() { return correctAnswer; }
    public void setCorrectAnswer(String correctAnswer) { this.correctAnswer = correctAnswer; }

    public Rubric getRubric() { return rubric; }
    public void setRubric(Rubric rubric) { this.rubric = rubric; }

    public boolean isTruncated() { return truncated; }
    public void setTruncated(boolean truncated) { this.truncated = truncated; }

    public Double getOcrConfidence() { return ocrConfidence; }
    public void setOcrConfidence(Double ocrConfidence) { this.ocrConfidence = ocrConfidence; }

    public double getParserConfidence() { return parserConfidence; }
    public void setParserConfidence(double parserConfidence) { this.parserConfidence = parserConfidence; }

    public Integer getPageNumber() { return pageNumber; }
    public void setPageNumber(Integer pageNumber) { this.pageNumber = pageNumber; }

    public BoundingBox getBoundingBox() { return boundingBox; }
    public void setBoundingBox(BoundingBox boundingBox) { this.boundingBox = boundingBox; }

    public List<String> getParserWarnings() { return parserWarnings; }
    public void setParserWarnings(List<String> parserWarnings) { this.parserWarnings = parserWarnings; }

    public ReviewStatus getReviewStatus() { return reviewStatus; }
    public void setReviewStatus(ReviewStatus reviewStatus) { this.reviewStatus = reviewStatus; }

    public String getTeacherNotes() { return teacherNotes; }
    public void setTeacherNotes(String teacherNotes) { this.teacherNotes = teacherNotes; }
}
